import { Inter } from "next/font/google";
import "../globals.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Log In",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html><body> <div className="h-screen w-full flex flex-col md:flex-row">{children}</div></body></html>
   
  );
}